spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true
    baseline-on-migrate: false

  cache:
    type: ${CACHE_TYPE:redis}

app:
  logging:
    aspect:
      slow-execution-threshold-ms: 2000

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

management:
  tracing:
    enabled: true
    sampling:
      probability: ${TRACING_SAMPLING_PROBABILITY:0.1}

logging:
  level:
    root: WARN
    com.example.boilerplate: INFO
